###
GET http://localhost:3050/api/projects
Authorization: Beaer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjM1MjQyMTk0LCJleHAiOjE2NDMwMTgxOTR9.O4kaFoN3TaIFHzZiWrx8Oc4-U-PN2LtAz-l28DbC7VU


###
GET http://localhost:3050/api/projects/2

###
POST http://localhost:3050/api/projects HTTP/1.1
content-type: application/json

{
  "title": "HTTP client Project"
}

###
PUT http://localhost:3050/api/projects/5 HTTP/1.1
content-type: application/json

{
  "title": "HTTP client Update Project"
}

###
DELETE http://localhost:3050/api/projects/3
